---
version: '3'
services:
  perforce:
    image: ambakshi/perforce-server
    hostname: perforce
    volumes:
      - p4depot:/data
    ports:
      - "1666:1666"
    env_file:
      - ./envfile
volumes:
  p4depot:
    external: true

# vim: sts=2:ts=2:sw=2:et:ft=yaml:
